# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  print_pipeline_id:
    description: "priniting circle ci pipeline ID"
    parameters:
      to:
        type: string
        default: "Pipeline ID"
    steps:
      - run: echo << parameters.to >>

jobs:
  printpipelineid_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id:
          to: $CIRCLE_WORKFLOW_ID


workflows:
  printing_pipeline_id:
    jobs:
      - printpipelineid_job
      